### ISSUE TITLE
Not able to update to latest version

### ISSUE THREAD

**Issue by rishabhk571** [kejonaMC/GeyserUpdater#87]
[06:37:00 ERROR]: [GeyserUpdater] Failed to download the newest build of Geyser
[06:37:00 WARN]: java.io.FileNotFoundException: https://ci.opencollab.dev/job/GeyserMC/job/Geyser/job/master/lastSuccessfulBuild/artifact/bootstrap/spigot/target/Geyser-Spigot.jar
[06:37:00 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1993)
[06:37:00 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
[06:37:00 WARN]:        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
[06:37:00 WARN]:        at GeyserUpdater-1.6.2.jar//com.projectg.geyserupdater.common.util.FileUtils.downloadFile(FileUtils.java:76)
[06:37:00 WARN]:        at GeyserUpdater-1.6.2.jar//com.projectg.geyserupdater.spigot.util.GeyserSpigotDownloader.downloadGeyser(GeyserSpigotDownloader.java:87)
[06:37:00 WARN]:        at GeyserUpdater-1.6.2.jar//com.projectg.geyserupdater.spigot.util.GeyserSpigotDownloader$1.run(GeyserSpigotDownloader.java:38)
[06:37:00 WARN]:        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101)
[06:37:00 WARN]:        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[06:37:00 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[06:37:00 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[06:37:00 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[06:37:00 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by rishabhk571** [comment]
![image](https://user-images.githubusercontent.com/89680511/191175957-d3cb0a14-660e-48a4-8d72-be26b196c5fa.png)
