### ISSUE TITLE
geyserupdate error

### ISSUE THREAD

**Issue by itcools** [kejonaMC/GeyserUpdater#97]
```diff
  [Fri 05:56:05 INFO  Geyser-Spigot] There's a new Geyser update available to support Bedrock version 1.20.0. Download it here: https://ci.geysermc.org
! [Fri 05:56:06 WARN  ViaVersion] There is a newer plugin version available: 4.7.0, you're on: 4.6.2
  [Fri 05:56:10 INFO ] [Log4jFixedChecker] Detected Version: git-Paper-388 (MC: 1.18.2)
  [Fri 05:56:10 INFO ] [Log4jFixedChecker] Detected Fix: VERSION118
  [Fri 05:56:10 INFO ] [Log4jFixedChecker] PASSED Found JVM argument '-Dlog4j2.formatMsgNoLookups=true'
  [Fri 05:57:09 INFO  GeyserUpdater] A newer build of Geyser is available! Attempting to download the latest build now...
- [Fri 05:57:10 ERROR GeyserUpdater] Failed to download the newest build of Geyser
! [Fri 05:57:10 WARN ] java.io.FileNotFoundException: https://ci.opencollab.dev/job/GeyserMC/job/Geyser/job/master/lastSuccessfulBuild/artifact/bootstrap/spigot/target/Geyser-Spigot.jar
! [Fri 05:57:10 WARN ] 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
! [Fri 05:57:10 WARN ] 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
! [Fri 05:57:10 WARN ] 	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
! [Fri 05:57:10 WARN ] 	at GeyserUpdater-1.6.2.jar//com.projectg.geyserupdater.common.util.FileUtils.downloadFile(FileUtils.java:76)
! [Fri 05:57:10 WARN ] 	at GeyserUpdater-1.6.2.jar//com.projectg.geyserupdater.spigot.util.GeyserSpigotDownloader.downloadGeyser(GeyserSpigotDownloader.java:87)
! [Fri 05:57:10 WARN ] 	at GeyserUpdater-1.6.2.jar//com.projectg.geyserupdater.spigot.util.GeyserSpigotDownloader$1.run(GeyserSpigotDownloader.java:38)
! [Fri 05:57:10 WARN ] 	at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101)```

**Comment by itcools** [comment]
> Update GeyserUpdater

It's the latest version

**Comment by Konicai** [comment]
Your download link isn't the same as the current one: <https://github.com/kejonaMC/GeyserUpdater/blob/main/src/main/java/com/projectg/geyserupdater/spigot/util/GeyserSpigotDownloader.java#LL78C19-L78C19>

make sure you're downloading form https://ci.kejona.dev/job/GeyserUpdater/job/main/

**Comment by itcools** [comment]
> Your download link isn't the same as the current one: https://github.com/kejonaMC/GeyserUpdater/blob/main/src/main/java/com/projectg/geyserupdater/spigot/util/GeyserSpigotDownloader.java#LL78C19-L78C19
> 
> make sure you're downloading form https://ci.kejona.dev/job/GeyserUpdater/job/main/

I'll get it again, install it, and tell you.

**Comment by itcools** [comment]
> Your download link isn't the same as the current one: https://github.com/kejonaMC/GeyserUpdater/blob/main/src/main/java/com/projectg/geyserupdater/spigot/util/GeyserSpigotDownloader.java#LL78C19-L78C19
> 
> make sure you're downloading form https://ci.kejona.dev/job/GeyserUpdater/job/main/

It's the same version, but I installed it again and it works well. Thank you.

**Comment by Konicai** [comment]
np
